# Generated by Django 4.2.8 on 2024-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_geniusera', '0003_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
    ]
